#!/bin/sh
#
# make snapshots for each jail without ZFS in jail
#
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
KEEPEXPR=${KEEPEXPR:-12l48h15d3w3m1y}

iocage_fs=$(zfs list -Honame /iocage/jails)
if [ -z "$iocage_fs" ]; then
  echo "pas de ZFS pour iocage :("
  exit 1
fi

zfs_snap_script="$(realpath $(dirname $0))/zfs_snap_make"
if ! [ -x "$zfs_snap_script" ]; then
  echo "impossible de trouver $zfs_snap_script"
  exit 1
fi

for j in $(iocage list -h | cut -w -f2); do
  if jls -v | grep -q 'ioc-'$j' *ACTIVE'; then
    [ $(iocage get -h jail_zfs $j) -eq 0 ] && $zfs_snap_script -r -c $KEEPEXPR -q "$iocage_fs/$j"
  fi
done
